fos_oauth_server:
  db_driver: orm       # Drivers available: orm, mongodb, or propel
  service:
    user_provider: security.provider.user_custom_provider

  client_class:        App\Entity\OAuth2\Client
  access_token_class:  App\Entity\OAuth2\AccessToken
  refresh_token_class: App\Entity\OAuth2\RefreshToken
  auth_code_class:     App\Entity\OAuth2\AuthCode