<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD2DwarY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD2DwarY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD2DwarY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD2DwarY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerD2DwarY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'D2DwarY',
    'container.build_id' => 'ede71409',
    'container.build_time' => 1618604260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD2DwarY');
